# Generated by Django 5.1.7 on 2025-03-13 07:01

import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_start', models.DateTimeField(db_index=True)),
                ('event_end', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPeople',
            fields=[
                ('registed_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=15, max_length=30, prefix='', primary_key=True, serialize=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
