# Generated by Django 5.1.7 on 2025-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_commentmodel_total_volunteered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='total_volunteered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
