# Generated by Django 5.1.7 on 2025-03-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
