# Generated by Django 5.1.7 on 2025-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='registered',
        ),
        migrations.AddField(
            model_name='registerpeople',
            name='registered_status',
            field=models.BooleanField(default=False),
        ),
    ]
