# Generated by Django 5.1.7 on 2025-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_commentmodel_total_volunteered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
