# Generated by Django 5.1.7 on 2025-03-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventmodel_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.locationmodel'),
        ),
    ]
