# Generated by Django 5.1.7 on 2025-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_campaignmodel_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='collected',
            field=models.PositiveIntegerField(default=0, help_text='Current progress of collected contributions'),
        ),
    ]
