# Generated by Django 5.1.7 on 2025-03-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_commentmodel_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent', 'Urgent')], db_index=True, default='Low', max_length=10),
        ),
    ]
