# Generated by Django 5.1.7 on 2025-03-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profilecauses_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilecauses',
            unique_together={('profile', 'cause')},
        ),
        migrations.AlterUniqueTogether(
            name='profileskills',
            unique_together={('profile', 'skill')},
        ),
    ]
