# Generated by Django 5.1.7 on 2025-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profilecauses_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='volunteer_status',
            field=models.BooleanField(default=False),
        ),
    ]
